site_name: Nathaniel Knickman
plugins:
  - search
  - macros
  - mkdocs-video:
      is_video: True
      video_muted: True
nav:
  - 'Programming':
    - 'C#': 'programming_cs.md'
    - 'C++': 'programming_cpp.md'
    - 'GDScript': 'programming_gdscript.md'
  - 'Art':
    - '2D': 'art_2d.md'
    - '3D': 'art_3d.md'
theme:
  palette:
    scheme: slate
    primary: custom
  name: material
  logo: assets/icons/icon.svg
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.sections
extra_css:
  - stylesheets/extra.css
extra:
  version:
    provider: mike
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: Sections